#ifndef _DEFINE_HPP
#define _DEFINE_HPP

// ONLY LEVEL A DIRECTIVES DEFINED CURRENTLY
enum Directive_type
{
    GLOBAL, EXTERN, SECTION, WORD, SKIP, END
};

enum Instruction_type
{
    PUSH, POP, XCHG,
    ADD, SUB, DIV, MUL,
    CMP, NOT, AND, OR, XOR, TEST, SHL, SHR,
    LDR, STR,
    IRET, HALT, RET, CALL, INT
};

enum Jump_type
{
    JMP, JEQ, JNE, JGT
};

enum Label_type
{
    SYMBOL, LITERAL, REGISTER
};

enum Addressing_type
{
    ABSOLUTE, MEMORY, PC_RELATIVE, LITERAL_OFFSET, SYMBOL_OFFSET
};

// IDEA IS THAT WE MIX LABEL TYPE WITH ADDRESSING TYPE AND THAT WAY GENERATE ALL COMIBNATIONS THAT WE CAN HAVE
// ALSO, WE CAN MAKE DATA_ADDRESSING_TYPE AND JUMP_ADDRESSING_TYPE TO HAVE DIFFERENCES BETWEEN JUMPS AND DATA

#endif